spring:
    datasource:
        password: pass
        url: jdbc:mysql://mysql:3306/sampledb
        username: user
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
